os: linux
dist: bionic
language: python
python: 3.6

branches:
  only:
    - "master"

before_install:
  - pip install cookiecutter
  - cd ..
  - cookiecutter schemaf --no-input
  - cd pmeier_schemaf
  - source .venv/bin/activate

jobs:
  include:
    - name: "Check cookiecutter code format"
      before_install: skip
      install: pip install isort black flake8
      script:
        - isort --settings-path=pyproject.toml --check-only --jobs=$(nproc) --recursive .
        - black --config=pyproject.toml --check .
        - flake8 --config=.flake8 --jobs=$(nproc) .
    - name: "Check project code format"
      install: pip install isort black flake8
      script:
        - JOBS=$(nproc)
        - isort --settings-path=pyproject.toml --check-only --jobs=$(nproc) --recursive .
        - black --config=pyproject.toml --check .
        - flake8 --config=.flake8 --jobs=$(nproc) .
    - name: "Check project static typing"
      install: pip install .[type_check]
      script: mypy --config-file=mypy.ini
    - name: "Run project tests"
      install: pip install .[test] coverage
      script: coverage run --rcfile=.coveragerc -m pytest -c pytest.ini
      after_success: coverage report
    - name: "Build project docs"
      install: pip install .[doc]
      before_script: cd docs
      script:
        - make html
        - make latex
        - make coverage
      after_success:
        - cd build/coverage
        - cat python.txt
