language: python
python: 3.6

matrix:
  include:
    - name: "Code format"
      before_install: pip install black
      install: skip
      script: black --check .
    - name: "Smoke test"
      before install: pip install cookiecutter
      install:
        - cd ..
        - cookiecutter schemaf --no-input
        - cd pmeier_schemaf
        - source .venv/bin/activate
      script:
        - black --check .
        - mypy
        - pytest
