[tool.isort]
# See link below for available options
# https://github.com/timothycrosley/isort/wiki/isort-Settings#full-reference-of-isort-settings

skip = [
  ".git",
  ".github",
  ".venv",
  ".tox",
  ".mypy_cache",
  "{{cookiecutter.package}}",
]
line_length = 88
use_parentheses = true
multi_line_output = 3
force_grid_wrap = 0
include_trailing_comma = true

known_standard_library = ["setuptools", "typing_extensions"]

[tool.black]
# See link below for available options
# https://github.com/psf/black#configuration-format

line-length = 88
target-version = ["py36"]
exclude = '''
/(
    \.git
  | \.github
  | \.venv
  | \.tox
  | \.mypy_cache
  | \{\{cookiecutter.package\}\}
)/
'''
