[tool.isort]
# See link below for available options
# https://timothycrosley.github.io/isort/docs/configuration/options/

profile = "black"
line_length = 88
skip_gitignore = true
float_to_top = true
order_by_type = true
combine_star = true
filter_files = true
skip = ["{{cookiecutter.slug}}"]

[tool.black]
# See link below for available options
# https://github.com/psf/black#configuration-format

line-length = 88
target-version = ["py36"]
exclude = "{cookiecutter.slug}"
