version: 2

sphinx:
  configuration: docs/source/conf.py

formats: all

python:
  version: {{cookiecutter.min_python_version}}
  install:
    - requirements: docs/requirements-rtd.txt
    - method: pip
      path: .
