name: tests

on:
  push:
    branches:
      - master

  pull_request:
    paths:
      - "{{cookiecutter.package}}/**"
      - "tests/**"
      - "pytest.ini"
      - "tox.ini"
      - "codecov.yml"
      - "requirements-dev.txt"
      - ".github/workflows/tests.yml"

jobs:
  run:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python: [{% for minor in range(cookiecutter.min_python_version[-1]|int, cookiecutter.max_python_version[-1]|int + 1) %}'3.{{minor}}'{{', ' if not loop.last }}{% endfor %}]
      fail-fast: true

    runs-on: {% raw %}${{ matrix.os }}{% endraw %}
    env:
      OS: {% raw %}${{ matrix.os }}{% endraw %}
      PYTHON: {% raw %}${{ matrix.python }}{% endraw %}

    steps:
      - name: Set up python
        uses: actions/setup-python@v2
        with:
          python-version: {% raw %}${{ matrix.python }}{% endraw %}

      - name: Upgrade pip and setuptools
        run: pip install --upgrade pip setuptools

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install dev requirements
        run: pip install -r requirements-dev.txt

      - name: Run tests
        run: tox -e py -- --skip-large-download

      - name: Upload coverage
        uses: codecov/codecov-action@v1.0.7
        with:
          env_vars: OS,PYTHON
