name: docs

on:
  push:
    branches:
      - master
      - releases/*

  pull_request:
    paths:
      - "{{cookiecutter.package}}/**"
      - "docs/source/**"
      - "setup.py"
      - "tox.ini"
      - "requirements-dev.txt"
      - ".github/workflows/docs.yml"

jobs:
  html:
    runs-on: ubuntu-latest

    steps:
      - name: Set up python
        uses: actions/setup-python@v2
        with:
          python-version: "{{cookiecutter.min_python_version}}"

      - name: Upgrade pip
        run: python -m pip install --upgrade pip

      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install dev requirements
        run: pip install -r requirements-dev.txt

      - name: Create environment
        run: tox -e docs-html --notest

      - name: Build html documentation
        run: tox -e docs-html -- -n -W --keep-going

      - name: Upload build
        uses: actions/upload-artifact@v2
        with:
          name: html
          path: docs/build/html
