name: tests

on:
  push:
    branches:
      - master
      - releases/*

  pull_request:
    paths:
      - "{{cookiecutter.package}}/**"
      - "tests/**"
      - "setup.cfg"
      - "pytest.ini"
      - "tox.ini"
      - ".coveragerc"
      - "codecov.yml"
      - "requirements-dev.txt"
      - ".github/workflows/tests.yml"

  schedule:
    - cron: "0 4 * * *"

jobs:
  run:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python: [{% for minor in range(cookiecutter.min_python_version[-1]|int, cookiecutter.max_python_version[-1]|int + 1) %}'3.{{minor}}'{{', ' if not loop.last }}{% endfor %}]
      fail-fast: true

    runs-on: {% raw %}${{ matrix.os }}{% endraw %}
    env:
      OS: {% raw %}${{ matrix.os }}{% endraw %}
      PYTHON: {% raw %}${{ matrix.python }}{% endraw %}

    steps:
      - name: Set up python
        uses: actions/setup-python@v2
        with:
          python-version: {% raw %}${{ matrix.python }}{% endraw %}

      - name: Upgrade pip
        run: python -m pip install --upgrade pip

      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install dev requirements
        run: pip install -r requirements-dev.txt

      - name: Create environment
        run: tox --notest

      - name: Run tests
        run: tox -- --skip-large-download

      - name: Upload coverage
        uses: codecov/codecov-action@v1.0.7
        with:
          env_vars: OS,PYTHON

  docs:
    runs-on: ubuntu-latest

    steps:
      - name: Set up python
        uses: actions/setup-python@v2
        with:
          python-version: "{{cookiecutter.min_python_version}}"

      - name: Upgrade pip
        run: python -m pip install --upgrade pip

      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Create environment
        run: tox -e tests-docs --notest

      - name: Run doctest
        run: tox -e tests-docs
