name: Docs

on:
  push:
    branches:
      - master
    paths:
      - "{{cookiecutter.pkg_name}}/**"
      - "docs/**"
      - ".github/workflows/build_docs.yml"

  pull_request:
    paths:
      - "{{cookiecutter.pkg_name}}/**"
      - "docs/**"
      - ".github/workflows/build_docs.yml"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Set up python
        uses: actions/setup-python@v1
        with:
          python-version: "{{cookiecutter.python_version}}"

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install dependencies
        run: pip install .[doc]

      - name: Build html
        working-directory: docs
        run: make html

      - name: Build latex
        working-directory: docs
        run: make latex

      - name: Build coverage
        working-directory: docs
        run: |
          make coverage
          cat build/coverage/python.txt
