name: Code format

on:
  push:
    branches:
      - master
    paths:
      - "**.py"
      - "pyproject.toml"
      - ".flake8"
      - ".github/workflows/code_format.yml"

  pull_request:
    paths:
      - "**.py"
      - "pyproject.toml"
      - ".flake8"
      - ".github/workflows/code_format.yml"

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - name: Set up python
        uses: actions/setup-python@v1
        with:
          python-version: "{{cookiecutter.python_version}}"

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install dependencies
        run: pip install isort black flake8

      - name: Check with isort
        run: isort --settings-path=pyproject.toml --check-only --jobs=$(nproc) --recursive .

      - name: Check with black
        run: black --config=pyproject.toml --check .

      - name: Check with flake8
        run: flake8 --config=.flake8 --jobs=$(nproc) .
