version: 2

sphinx:
  configuration: docs/source/conf.py

formats: all

python:
  version: {{cookiecutter.python_version}}
  install:
    - method: pip
      path: .
      extra_requirements:
        - doc
