language: python
python: "{{cookiecutter.python_version}}"

matrix:
  include:
    - name: "Code format"
      before_install: pip install black
      install: skip
      script: black --check .
    - name: "Type checks"
      install: pip install .[type_check]
      script: mypy --config-file=mypy.ini {{cookiecutter.pkg_name}}/
    - name: "Tests"
      before install: pip install coverage codecov
      install: pip install .[test]
      script: coverage run --rcfile=.coveragerc -m pytest -c pytest.ini
      after success: codecov
