os: linux
dist: bionic
language: python
python: {{cookiecutter.python_version}}

jobs:
  include:
    - name: "Code format"
      install: pip install isort black flake8
      script:
        - isort --settings-path=pyproject.toml --check-only --jobs=$(nproc) --recursive .
        - black --config=pyproject.toml --check .
        - flake8 --config=.flake8 --jobs=$(nproc) .
    - name: "Type checks"
      install: pip install .[type_check]
      script: mypy --config-file=mypy.ini
    - name: "Tests"
      install: pip install .[test] coverage codecov
      script: coverage run --rcfile=.coveragerc -m pytest -c pytest.ini --skip-large-download
      after_success:
        - coverage report
        - codecov