name: cookiecutter

on:
  push:
    branches:
      - master

  pull_request:
    paths:
      - "hooks/**"
      - "pyproject.toml"
      - ".flake8"
      - "mypy.ini"
      - "tox.ini"
      - "requirements-dev.txt"
      - ".github/workflows/cookiecutter.yml"

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Set up python
        uses: actions/setup-python@v2
        with:
          python-version: "3.6"

      - name: Upgrade pip
        run: python -m pip install --upgrade pip

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install development requirements
        run: pip install -r requirements-dev.txt

      - name: Lint
        run: tox -e lint
